# Generated by Django 4.1.2 on 2023-04-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('sprite', models.CharField(max_length=250)),
                ('sexo', models.CharField(choices=[('V', 'Macho'), ('M', 'Hembra'), ('N', 'Neutro')], max_length=1)),
                ('afinidad', models.CharField(choices=[('A', 'Aire'), ('T', 'Tierra'), ('M', 'Montaña'), ('B', 'Bosque'), ('N', 'Neutro')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sprite', models.CharField(max_length=250)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('obtencion', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supertecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('afinidad', models.CharField(choices=[('A', 'Aire'), ('T', 'Tierra'), ('M', 'Montaña'), ('B', 'Bosque'), ('N', 'Neutro')], max_length=1)),
                ('tipo', models.CharField(choices=[('B', 'Bloqueo'), ('T', 'Tiro'), ('R', 'Regate'), ('A', 'Atajo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PE', 'Puntos de Energia'), ('PT', 'Puntos de tecnica'), ('T', 'Tiro'), ('F', 'Fisico'), ('C', 'Control'), ('D', 'Defensa'), ('R', 'Rapidez'), ('A', 'Aguante'), ('V', 'Valor'), ('S', 'Suerte'), ('L', 'Libertad')], max_length=300)),
                ('valor', models.IntegerField(max_length=3)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InazumaApp.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorSupertecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InazumaApp.jugador')),
                ('supertecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InazumaApp.supertecnica')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorClubTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InazumaApp.club')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InazumaApp.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InazumaApp.temporada')),
            ],
        ),
    ]
